# Site settings
title: Mr. Jing
SEOTitle: Scott Jing's Homepage
header-img: img/website/home-bg.jpg
email: tomjayad@gmail.com
description: "Scott's Homepage"
keyword: "Scott, Blog, Homepage"
url: "scottjingtt.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
# RSS: false
# weibo_username:     
zhihu_username:     
github_username:    scottjingtt
twitter_username:   
facebook_username:  
linkedin_username:  taotaojing/




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: 

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-153423132-1'            # Format: UA-xxxxxx-xx
ga_domain: scottjingtt.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Scott Jing"
sidebar-avatar: /img/website/scott_sunrise.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Links
friends: [
    {
        title: "Dr. Zhengming (Allan) Ding",
        href: "http://www.cs.tulane.edu/~zding1/"
    },
    {
        title: "Dr. Hongfu Liu",
        href: "http://hongfuliu.com/"
    },
    {
        title: "Dr. Jihun Hamm",
        href: "http://www.cs.tulane.edu/~jhamm3/"
    },
    {
        title: "Dr. Renran Tian",
        href: "https://et.iupui.edu/people/rtian"
    },
    {
        title: "Dr. Lichen Wang",
        href: "https://sites.google.com/site/lichenwang123/"
    },
    {
        title: "Dr. Yun Raymond Fu",
        href: "http://www1.ece.neu.edu/~yunfu/"
    },
    {
        title: "Dr. Bingrong Xu",
        href: "https://dblp.org/pid/208/8098.html"
    },
    {
        title: "Haifeng Xia",
        href: "https://haifengxia.github.io/"
    }
]

links: [
      {
        title: "Tulane University",
        href: "https://tulane.edu/"
    },
    {
        title: "SmileLab",
        href: "https://web.northeastern.edu/smilelab/"
    },
    {
        title: "CS Rankings",
        href: "http://csrankings.org/#/fromyear/2011/toyear/2021/index?all&us"
    },
    {
        title: "AI Rankings",
        href: "https://airankings.org/#scope=world&fromYear=2011&toYear=2021&sort=adj&venues=agi%7Cuai%7Cjair%7Caaai%7Cijcai%7Cpami%7Cijcv%7Ccviu%7Cpr%7Cftcgv%7Ccvpr%7Ciccv%7Ceccv%7Csr%7Cicra%7Ciros%7Cro-man%7Crss%7Cjmlr%7Cneco%7Cijon%7Cnips%7Cicml%7Ccolt%7Caistats%7Ciclr%7Cacl%7Cemnlp%7Ccoling%7Cconll%7Cnaacl%7Ccogsci%7Ccogsciconf%7Caamas%7Cjaamas%7Csagt%7Calife%7Ceurographics%7Csiggraph%7Csiggraph-asia%7Ctog%7Cvr"
    },
    {
        title: "Transfer Learning",
        href: "https://github.com/jindongwang/transferlearning"
    },
    {
        title: "Domain Adaptation",
        href: "https://github.com/zhaoxin94/awesome-domain-adaptation"
    }]

collects: [
    {
        title: "Pedestrian Situated Intent Dataset",
        href: "https://github.com/PSI-Intention2022/PSI-Intention"
    },
    {
        title: "Awesome Explainable/Interpretable Transfer Learning (XTL)",
        href: "https://github.com/scottjingtt/awesome-interpretable-transfer-learning"
    },
    {
        title: "Awesome Pedestrian Behavior Estimation",
        href: "https://github.com/PSI-Intention2022/awesome-pedestrian-behavior-estimation"
    }]